version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
      - mvn test
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - 'target/orderservice.jar'
  discard-paths: yes